name: wm_com_ivanna
description: A new Flutter project.
publish_to: 'none'
version: 2.3.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  dio: ^5.0.2
  intl: ^0.18.0 
  get: ^4.6.5
  get_storage: ^2.1.1
  sembast: ^3.4.2
  sembast_web: ^2.1.1
  path_provider: ^2.0.10 
  path: ^1.8.2 
  pluto_grid: ^6.0.4

  omni_datetime_picker: ^1.0.1
  badges: ^3.0.2
  url_launcher: ^6.0.18
  google_fonts: ^4.0.3
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.1
  syncfusion_flutter_charts: ^21.1.35
  syncfusion_flutter_datagrid_export: ^21.1.35
  syncfusion_flutter_barcodes: ^21.1.35
  syncfusion_flutter_calendar: ^21.1.35
  syncfusion_flutter_pdfviewer: ^21.1.35 
  simple_speed_dial: ^0.1.3   
  flutter_switch: ^0.3.2
  flutter_staggered_grid_view: ^0.6.1
  flash_card: ^0.0.7
  pdf: ^3.8.0  
  file_picker: ^5.2.3
  extended_image: ^7.0.2
  excel: ^2.0.0-null-safety-3  
  davi: ^3.2.0
  flutter_slidable: ^2.0.0 
  flutter_breadcrumb: ^1.0.1
  flutter_quill: ^6.3.5  # sauf le android
  open_app_file: ^4.0.1
  cached_network_image_builder: ^0.2.0
  printing: ^5.9.3 
  flutter_typeahead: ^4.3.3 
  get_time_ago: ^1.2.2
  field_suggestion: ^0.2.5  
  calendar_date_picker2: ^0.4.6
  syncfusion_flutter_xlsio: ^21.1.35
  internet_connection_checker: ^1.0.0+1
  firebase_core: ^2.8.0 # Window & Linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.6.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic  

msix_config:
  display_name: Ivanna
  publisher_display_name: wm_com_ivanna
  identity_name: com.eventdrcTechnology.WorkManagement
  msix_version: 2.2.1.0
  certificate_path: C:\Users\K-GERMANDO\Documents\DEVELOPER\FLUTTER\CERTIFICAT\wm_commercial_certifat\CERTIFICATE.pfx
  certificate_password: tMvBcb4KGAIX9xIF
  publisher: CN=Germain kataku, O=Eventdrc Technology
  logo_path: C:\Users\K-GERMANDO\Documents\DEVELOPER\FLUTTER\PROJECT\wm_com_ivanna\assets\images\logo_fond.png
  start_menu_icon_path: C:\Users\K-GERMANDO\Documents\DEVELOPER\FLUTTER\PROJECT\wm_com_ivanna\assets\images\logo_fond.png
  tile_icon_path: C:\Users\K-GERMANDO\Documents\DEVELOPER\FLUTTER\PROJECT\wm_com_ivanna\assets\images\logo_fond.png
  # vs_generated_images_folder_path: C:\<PathToFolder>\icons
  icons_background_color: '#ffffff'
  architecture: x64
  capabilities: 'internetClient,location,microphone,webcam'
